### ISSUE TITLE
colored icons

### ISSUE THREAD

**Issue by paskuale75** [simialbi/yii2-elfinder#20]
Is there a way to make the icons of the files colored ? Pdf red .... word blue ... etc

thanks

**Comment by simialbi** [comment]
could you create an object in the support-01 account? So I could have a look?

**Comment by simialbi** [comment]
you can do it via css (e.g. word):
```css
.elfinder-cwd .elfinder-cwd-file .elfinder-cwd-icon.elfinder-cwd-icon-vnd-openxmlformats-officedocument-wordprocessingml-document {
    color: blue;
}
```
